services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8080"
    volumes:
      - ./backend:/app
      - /app/tmp
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PORT=8080
      - DATA_DIR=/app/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
